var famousPerson = 'Beyonce';
var isActive = true;
famousPerson = 'Rihanna';
var num3 = 10;
var num9 = 27;
var sum = num3 + num9;
var animals = ['cats', 'dogs', 'kangaroos'];
animals.shift();
var len = famousPerson.length;
cosole.log(len);
